---
title: "Book Notes: War of Art"
date: 2021-10-25T18:14:15+05:30
draft: true
---

#+Title: The War of Art
#+Author: Tushar Singh Parte
#+TAGS: @books @learning

* The War of Art
To begin book one, Pressfield labels the enemy of creativity Resistance, his
all-encompassing term for what Freud called the Death Wish- that destructive
force inside human nature that rises whenever we consider a tough, long-term
course of action that might do for us or others that's actually good. He then
presents a rogue's gallery of the many manifestations of Resistance.

In the second book, Pressfield lays out the day-by-day, step-by-step campaign of
the professional: preparation, order, patience, endurance, acting in the face of
fear and failure- no excuses, no bullshit.

Book three, looks at Inspiration, that sublime result that blossoms in the
furrows of the professional who straps on the harness and plows the filds of his
or her art.

#+begin_quote
There's a secret that real writers know that wannabe writers don't, and the
secret is this: It's not the writing part that's hard. What's hard is sitting
down to write. What keeps us from sitting down is Resistance.
#+end_quote

* THE UNLIVED LIFE
Most of us have two lives. The life we live, and the unlived life within us.
Between the two stands resistance. Late at night have you experienced a vision
of the person you might become, the work you could accomplish, the realized
being you were meant to be? Are you a writer who doesn't write, a painter who
doesn't paint, an entrepreneur who never starts a venture? Then you know what
resistance is.

+ Resistance is the most toxic force on the planet.
 
Have you heard this story: Woman learns that she has cancer, six months to live.
Within days she quits her job, resumes the dream of writing Tex-Mex songs she
gave up to raise a family (or starts studying classical Greek, or moves to the
inner city and devotes herself to tending babies with AIDS). Woman's friends
think she's crazy; she herself has never been happier. There's a postscript.
Woman's cancer goes into remission. So is it what it takes?

** BOOK ONE: RESISTANCE DEFINING THE ENEMY
It's a repelling force. It's negative. Its aim is to shove us away, distract us,
prevent us from doing our work. Resistance is not a peripheral opponent. It
arises from within. It will tell you anything to keep you from doing your work.
It will reason with you like a lawyer or jam a nine-milimeter in your face like
a stickup man. It is always lying and always full of shit. 

The more important it is, the more resistance you will feel. The fear doesn't go
away. The warrior and the artist live by the same code of necessity, which
dictates that the battly must be fought anew everyday.
+ Resistance is most powerful at the finsh line.
Resistance recruits allies.
#+begin_quote
The highest treason a crab can commit is to make a leap for the rim of the bucket.
#+end_quote

The best and the only thing one artist can do for another is to serve as an
example and insipiration.
+ Procrastination is the most common manifestation of resistance because it's
  the easiest to rationalize.

We don't just put off our lives today; we put them off till our deathbed.

#+begin_quote
Never forget: This very moment, we can change our lives. There never was a
moment, and never will be, when we are without the power to alter our destiny.
This second we can turn the tables on Resistance. This second, we can sit down
and do our work.
#+end_quote

+ The working artist will not tolerate trouble in her life because she knows
  trouble prevents her from doing her work. The working artist banishes from her
  world all sources of trouble. She harnesses the urge for trouble and
  transforms it in her work.

+ Resistance and Self-Dramatization
Creating soap opera in our lives is a symptom of resistance. Why put in years of
work designing a new software interface when you can get just as much attention
by bringing home a boyfriend with a prison record? Sometimes entire families
participate unconsciously in a culture of self-dramatization.

+ Depression and anxiety may be real. But they can also be resistance. Instead
  of applying self-knowledge, self-discipline, delayed gratification, and hard
  work, we simply consume a product.

+ Doctors estimate that seventy to eighty percent of their business is
  non-health-related. People aren't sick, they're self-dramatizing. Sometimes
  the hardest part of a medical job is keeping a straight face.

A victim act is a form of passive aggression. It seeks to achieve gratification
not by honest work or a contribution made out of one's experience or insight or
love, but by the manipulation of others through silent (and not-so-silent)
threat. The victim compels others to come to her rescue or to behave as she
wishes by holding them hostage to the prospect of her own further
illness/meltdown/mental dissolution, or simply by threatening to their lives so
miserable that they do what she wants.

+ Sometimes, if we are not conscious of our own resistance, we will pick as a
  mate someone who has or is successfully overcoming resistance. Maybe we are
  hoping to use our mate as a model.

*** What does Resistance feel like?
+ Unhappiness. We feel bored, we're restless, We can't get no satisfaction.
  There's guilt but we can't put our finger on the source. We want to go back to
  bed; we want to get up and party. We feel unloved and unlovable. We are
  disusted. We hate our lives. We hate ourselves. At this point vice kick in.
  Dope, adultery, web surfing. Resistance becomes clinical. Depression,
  aggression, dysfunction. Then actual crime and physical self-distruction.

*** Resistance and Fundamentalism?
The artist and the fundamentalist both confront the same issue, the mystery of
their existence as individuals. Each asks the same questions:
+ Who am I?
+ Why am I here?
+ What is the meaning of my life?
At more primitive stages of evolution, humanity didn't have to deal with such
questions. These are not easy questions. They're not easy because the human
being isn't wired to function as an individual. We're wired tribally, to act as
part of a group. Our psyches are programmed by millions of years of
hunter-gatherer evolution. We don't know how to be free individuals.

Fundamentalism is the philosophy of the powerless, the conquered, the displaced
and the dispossessed. Its spawning ground is the wreakage of political and
military defeat, as Hebrew fundamentalism arose during the Babylonian captivity,
as white Cristian fundamentalism appeared in the Americal South during
Reconstruction, as the notion of the Master Race evolved in Germany following
World War I. In such desperate times, the vanquished race would perish without
a doctorine that restored hope and pride. Islamic fundamentalism ascentds from
the same landscape of despair and possesses the same tremendous and potent
appeal. He cannot find his way into the future, so he retreats to the past. He
returns in imagination to the glory days of his race and seeks to recontitute
both them and himself in their purer, more virtuous light. He gets back to
basics. To fundamentals. Resistance to the fundamentalist is the call of the
Evil One, seeking to seduce hum form his virtue. The fundamentalist is consumed
with Satan, whom he loves as he loves death. To combat the call of sin i.e.
Resistance, the fundamentalist plunges either into action or into the study of
sacred texts. He loses himself in these, seeking to return to a purer world from
which he and all have fallen.

The humanist belives that humankind, as individuals, is called upon to co-create
the world with God. This is why he values human life so highly. In his view,
things do progress, life doesn evolve; each indiviudal has value,a t least
potentially, in advancing this cause.

When fundamentalism wins, the world enters a dark age.

It may be that human race is not ready for freedom. The air of liberty may be
too rarefied for us to breathe.

#+begin_quote
"The truely free individual is free only to the extent of his own self-mastery"
--- Socrates
#+end_quote

Those who will not govern themselves are condemned to find masters to govern
over them.

*** Resistance and Criticism
When we see others beginning to live their authentic lives, it drives us crazy
if we have not lived out our own.

Individuals who are realised in their own lives almost never criticize others.
If they speak at all, it is to offer encouragement. Watch yourself.

*** Resistance and Self-Doubt
Self-doubt can be an ally. This is because it serves as an indicatore of
aspiration. If you find yourself asking yourself (and your friends, "Am I really
a writer? Am I really an artist" chances are you are.

*** Resistance and Fear
Are you paralyzed with fear? That's a good sign.

Fear is good. Like self-doubt, fear is an indicator, it tells us what we have to
do. The more scared we are of a work or calling, the more sure we can be that we
have to do it.

*** Resistance and Love
Resistance is directly proportional to love. If you are feeling massive
resistance, teh good news is, it means there's tremendous love there too. If you
didn't love the project that is terrifying you, you wouldn't feel anything. The
opposite of live isn't hate; it's indifference.

*** Resistance and Being a Star
Grandiose fantasies are a sign of resistance. They are a sign of an amateur. The
professional concentrates on the work and allows rewards to come or not come,
whatever they like.

*** Resistance and Isolation
Sometimes we balk at embarking on an enterprise because we're afraid of being
alone. We feel comfortable with the trive arond us; it makes us nervous going
off into the woods on our own.

Friends sometimes asl, "Don't you get lonely sitting by yourself all day?" At
first it seemed odd ot head myself answer No. Then I realised that I was not
alone; I was in the book; I was with the characters. I was with my self.
*** Resistance and Healing
The athlete knows the day will never come when he wakes up pain-free. He has to
play hurt. The part of us we imagine needs healing is not the part we create
from; that part is far deeper and stronger. The part that needs healing is our
personal life. Personal life has nothing to do with work. Resistance loves
"healing". Resistance knows that the more psychic energy we expend dredging and
re-dredging the tired, boring injustices of our personal lives, the less juice
we have to do our work.
*** Resistance and Support
Seeking support from friends and family is like having people gathered around at
your deathbed. It's nice, but when the ship sails, all they can do is stand at
the dock waving goodbye. The more energy we spend stoking up on support from
colleagues and loved ones, the weaker we become and the less capable of handling
our business.
*** Resistance and Rationalization
#+begin_quote
Aw, come on! Nothing's more important than sex.
#+end_quote
have you ever gone a week without rationalization?

Resistance is fear. But resistance is too cunning to show itself naked in this
form. Why? Because if resistance lets us see clearly that our own fear is
preventing us form doing our work, we may feel shame on this. It doesn't want
this. So it brings in Rationalization. It presents us with a series of
plausible, rational justifications for why we shouldn't do our work and it makes sense.
** BOOK TWO: COMBATING RESISTANCE. Turning Pro
#+begin_quote
It is one thing to study war and another thing to live the warrior's life.
#+end_quote
Aspiring artists defeated by Resistance share one trait. They all think like
amateurs. They have not yet turned pro.

To be clear: When the author says professional, he doesn't mean doctors and
lawyers. He means the Professional as an ideal. The amateur plays for fun. The
professional plays for keeps. The amateur plays part-time, the professional
full-time. The amateur is a weekend warrior, the professional is there seven
days a week. The amateur does not love the game enough.

#+begin_quote
Someone once asked Somerset Maugham if he wrote on a schedule or only when stuck
by inspiration. "I write only when inspiration striks," he replied. "Fortunately
it strikes every morning at nine o' clock sharp."
#+end_quote

Be aware of the Principle of Priority, which states
+ you must know the difference between what is urgent and what is important
+ you must do what is important first.

What is important is work. That's the game I have to suit up for.

#+begin_quote
We may take pride in our work, we may stay late and come in on weekends, but we
recognize that we are not our job descriptions. The amateur, on the other hand,
overidentifies with his avocation, his artistic aspiration. He defines himself
by it. He is a musician, a painter, a play wright. Resistance loves this.
Resistance knows that the amateur composer will never write his symphony because
he is overly invested in its success and overterrified of its failure. The
amateur takes it so seriously it paralyzes him.
#+end_quote

How does an amateur pursue his calling?
+ He does not show up everyday.
+ He does not show up no matter what.
+ He does not stay on the job all day.
+ He is not committed over the long haul.
+ The stakes for him are illusory and fake.
+ He does not get money.
+ He overidentifies with his art.
+ The amateur hasn't mastered the technique of his art.

#+begin_quote
Nothing is as empowering as real-world validation, even if it's for failure
#+end_quote

The professional, though he accepts moeny, does his work out of love. He has to
love it. Otherwise he wouldn't devote his life to it of his own free will.

It uses his own enthusiasm againt him. Resistance gets us to plunge into a
project with an overambitious and unrealistic timetable for its completion. It
knows we can't sustain that level of intensity. We will hit the wall, we will
crash.

The professional arms himself with patience, not only to give the stars time to
align in his career, but to keep himself from flaming out in each individual
work. The professional shuts up. She doesn't talk about it. She does her work.

The amateur believes he must first overcome his fear; then he can do his work.
The professional knows that fear can never be overcome. He knows there is no
such thing as a fearless warrior or a dread-free artist.

The professional knows that resistance is like a telemarketer; if you so much as
say hello, you're finished. The pro doesn't even pick up the phone. He stays at
work.

#+begin_quote
A professional, does not show off.
#+end_quote

+ A professional dedicates himself to mastering the technique.
+ A professional does not hesitate to ask for help.
+ A professional does not take failure (or success) personally. The professional
  cannot let himself take humilation perosnally. Humiliation, like rejection and
  criticism, is the external reflection of internal Resistance. The professional
  keeps his eye on the doughnut and not on the hole. He reminds himself it's
  better to be in the arena, getting stomped by the bull, than to be up in the
  stands or out in the parking lot.
+ A professional self-validates. He cannot allow the actions of others to define
  his reality. Tomorrow morning the critic will be gone but the writer will
  still be there facing the blank page. Nothing matters but that he keep
  working. He learns to recognize every envy-driven criticism and to take it for
  what it is: the supreme compliment. The critic hates most that which he would
  have done himself if he had the guts.
+ A professional recognizes her limitations.
+ A professional is recignized by other professionals.

#+begin_quote
There's no mystery to turning pro. It's a decision brought about by an act of
will. We make up our mind to view ourselves as pros and we do it. Simple as that.
#+end_quote
** BOOK THREE: BEYOND RESISTANCE. Higher Realm
The next few chapers are going to be about those invisible psychic forces that
support and sustain us in our journey towards ourselves.

Nothing else matters except sitting down everyday and trying. Because when we
sit down day after day and keep grinding, something mysterious starts to happen.
A process is set into motion by which, inevitably and fallibly, heaven comes to
our aid. Unseen forces enlist in our cause; serendipity reinforces our purpose.

*** Muses
The muses were nine sisters, daughters of Zeus and Mnemosyne, which means
"memory". Their names are CLie, Erato, Thalia, Terpsichore, Calliope,
Polyhumnia, Euterpe, Melpomene, and Urania. Their job is to inspire artists.
Each Muse is responsible for a different art.

*** Life and Death
The moment a person learns he's got terminal cancer, a profound shift takes
place in his psyche. At one stroke in the doctor's office he becomes aware of
what really matters to hi. Things that sixty seconds earlier had seemed all
important suddenly appear meaningless, while people and concerns that he had
till then dismissed at once take on supreme importance.

Maybe, he realizes, working this weekend on that big deal at the office isn't
all that vital. Maybe it's more important to fly cross-country for his
grandson's graduation. maybe it isn't so crucial that he have the last word in
the giht with his wife. Maybe instead he should tell her how much she means to
him and how deeply he has always loved her.

Faced with our imminent extinction, Tom Laughlin believes, all assumptions into
question.
+ What does our life mean?
+ Have we lived it rihgt?
+ Are there vital acts we've left unformed, crucial words unspoken?
+ Is it too late?

*** The Ego and the Self
The self wishes, to create, to evolve, the ego likes things just the way they
are.

The Ego is that part of the psyche that believes in material existence. What Ego
believes:
1. Death is real.
2. Time and space are real.
3. Every individual is different and separate from every other.
4. The predominant impulse of life is self-preservation.
5. There is no god.

What self believes:
1. Death is an illusion.
2. Time and space are illusions.
3. All beings are one.
4. The supreme emotion is love
5. God is all there is.

*** Experiencing the Self
The Self is our deepest being.
The Ego hates Self because when we seat our consciousness in the self, we put
the ego out of business.

*** FEAR
Fear is the consequence of following our heart. Fear of backruptcy, fear of
poverty, fear of insolvency. Fear of groveling when we try to make it on our
own.

All of these and many more are serious fears. But they are not the real fear.
Not the Master Fear, the Mother of all Fears that's so close to us that even
when we verbalize it we don't believe it.

Fear That We Will Succeed.
That we can access the powers we secretly know we posses.
That we can become the person we sense in our hearts we truely are.

We fear discovering that we are more than we think we are. More than our
parents/children/teachers think we are. We fear that we actually posses the
talent that our still, small voice tells us. That we actually have the guts, the
perseverance, the capacity. We fear that we truely can steer our ship, plant our
flag, reach our Promised Land.

We know that if we embrace our ideals, we must prove to be worth of them. And
that scares the hell out of us. What will become of us? We will lose our friends
and family, who will no longer recognize is. We will wind up alone, in the cold
void of starry space, with nothing and no one to hold on to.

We wind up in space, but not alone, Instead we are tapped into an unquenchable,
undepletable, inexhaustible source of wisdom, consciousness, companionship. Yeah
we lose friends. But we find friends too, in places we never thought to look.
And they're better friends, truer friends. And we are better and truer to them.

*** The Authentic Self
None of use are born as passive generic blobs waiting for the world to stamp its
imprint to us. Instead we show up possessing already a highly refined and
individual soul. We are not born with unlimited number of choices. We can't be
anything we want to be. We come into this world with a specific, personal
destiny. We have a job to do, a calling to enact, a self to become.

Our job in this lifetime is not to shape ourselves into some ideal we imagine we
outght to be, but to find out who we already are and become it.

#+begin_quote
To labor in the arts for any reason other than love is prostitution.
#+end_quote

*** Orientation
+ Territorial
+ Hierarchical


#+begin_quote
In the hierarchy, the artist looks up and looks down. The one place he can't
look is that place he must: within.
#+end_quote

*** The Artist and the Territory
The act of creation is by definition territorial.

#+begin_quote
Of any activity, you do, ask yourself: If I were the last person on earth, would
I still do it?
#+end_quote

When Krishna instructed Arjuna that we have a right to our labor but not to the
fruits of our labor, he was conseling the warrior to act territorially, not
hierarchically. We must do our work for its own sake, not for fortune or
attention or applause.

To labor in this way, /The Bhagvad-Gita/ tells us, is a form of meditation and a
supreme species of spiritual devotion. It also, I belive, conforms most closely
to Higher Reality.

Every breath we take, every heartbeat, every evolution of every cell comes from
God and is sutained by God every seocnd, just as every creation, invention,
every bar of music or line of verse, every thought, vision, fantasy, every
dumb-ass flop and stroke of genious comes from that infinite intelligence that
created us and the universe in all its dimensions, out of the Void, the field of
infinite potential, primal chaos, the Muse. To acknowledge that reality, to
efface all ego, to let the work come through us and give it back freely to its
source, that, in my opinion is as true to reality as it get.

*** The Artist's Life
Are you a born writer? Were you put on earth to be a painter, a scientist, an
apostle of peace? In the end the question can only be answered by action.

Do or don't do it.

If you were meant to cure cancer or write a symphony or crack cold fusion and
you don't do it, you not only hurt yourself, even distroy yourself. You hurt
your children. You hurt me. You hurt the plant.

Creative work is not a selfish act or a bid for attention on the part of the
actor. It's a gift to the world and every being in it. Don't cheat us of your
contribution. Give us what you've got.

