---
title: "Book Notes: Essentialism"
date: 2021-12-30T12:28:16+05:30
draft: true
---

* The essentialist

#+begin_quote
Instead of making just a millimeter of progress in a million directions, begin to generate tremendous momentum towards accomplishing the things that are truly vital.
#+end_quote

Only once you give yourself permission to stop trying to do it all, to stop saying yes to everyone, can you make your highest contribution towards the things that really matter.

How many times have you reacted to a request by saying yes without really thinking about it?

** The Way of the Essentialist

The way of the Essentialist is the relentless pursuit of less but better. It's about pausing constantly to ask, "Am I investing in the right activities?" There are far more activites in the world than we have time and resources to invest in but most are trivial and few are vital.

Essentialism is not about how to get more things done; it's about how to get the /right/ things done. By investing in fewer things we have the satisfying experience of making significant progress in the things that matter the most. Essentialist rejects the idea that we can fit it all in.

Essentialism is a disciplined, systematic approach for determining where our highest point of contribution lies, then making exection of those things almost effortless.
** The Way of the Nonessentialist

#+begin_quote
If you don't prioritize your life, someone else will.
#+end_quote

In our society we are punished for good behaviour (saying no) and rewarded for bad behavior (saying yes). It often leads to what the author calls "the paradox of success" summarized in 4 phases:

- *Phase 1:* When we really have clarity of purpose, it enables us to succeed at our endeavor.
- *Phase 2:* When we have success, we gain a reputation as a "go to person" and we are presented with increased options and opportunities.
- *Phase 3:* When we have increased opportunties and options, which is actually code for demands upon our time and energies, it leads to diffused efforts.
- *Phase 4:* We become distracted from what would otherwise be our highest level of contribution.

  #+begin_quote
  The persuit of success can be a catalyst for failure
  #+end_quote

** Why Nonessentialism is everywhere
+ Too many choices
+ Too much social pressure
+ The idea that "you can have it all"

#+begin_quote
We can either make our choices deliberately or allow other people's agendas to control our lives.
#+end_quote

Essentialism is about creating a system for handling the closet of our lives. This is not a process you undertake once a year, once a month, or even once a week. It's a discipline you apply each and every time you are faced with a decision about whether to say yes or whether to politely decline. It's a method for making the tough trade-off between lots of good things and a few really great things.

** Road map
*** Step 1: explore
Essentialists actually expore more options than their nonessentialist counterparts. Rather than virually committing to everything without actually exploring, essentialists explore and evaluate a broad set of options before committing to any.

We aren't looking for plethora of good things to do. We are looking for our highest level of contribution: the right thing the right way at the right time.

*** Step 2: eliminate
People are effective because they say 'no', because they say, 'this isn't for me'.

*** Step 3: execute
We tend to think of the process of execution as something hard and full of friction, something we need force to "make happen". Instead of forcing execution, Essentialists invest the time they saved into creating a system for removing obstacles and making execution as easy as possible.
* Choose

#+begin_quote
It is the ability to choose which makes us human.
#+end_quote

The ability to choose cannot be taken away or even given away - it can only be forgotten.

** How do we forget our ability to Choose ?

Because of *learned helplessness*.

To become an Essentialist requires a hightened awareness of our ability to choose.

#+begin_quote
"I have to" --- Nonessentialist
#+end_quote

#+begin_quote
"I choose to" --- Essentialist
#+end_quote
* Discern

Is there a point at which doing more does /not/ produce more? Is there apoint at which doing /less/ (but thinking more) will actually produce better outcomes?

Certain types of effort yield higher rewards than others. Working hard is important. But more effort does not necessarily yield more results. "Less but better" does.

World's greatest chef, Ferran Adria has led El Bulli to become the world's most famous restaurant using the principle of "less but better". His specialty is reducing traditional dishes to their absolute essence and then re-imagining them in ways people have never thought of before. El Bulli has somewhere in the range of 2 million requests for dinner reservations each year, it serves only fifty people per night and closes for six months of the year.

"Less but better" is harder than it sounds especially when you are rewarded in the past for "more and more".

"Warren decided early in his career it would be impossible for him to make hundreds of right investment decisions, so he decided that he woul dinvest only in the business that he was absolutely sure of, and then bet heavily on them. He owes 90% of his wealth to just ten investments."

According to "power law theory", certain efforts actually produce exponentially more results than others.

The overwhelming reality is: we live in a world where almost everything is worthless and a very few things are exceptionally valuable.

#+begin_quote
"You cannot overestimate the unimportance of practically everything" --- John Maxwell
#+end_quote

#+begin_quote
A nonessentialist things almost everything is essential.
#+end_quote

#+begin_quote
A essentialist things almost everything is nonessential.
#+end_quote
* Trade-off

You have to look at every opportunity and say, "Well, no... I'm sorry. We're not going to do a thousand different things that really won't contribute much to the end result we are trying to achieve."

Look at the approach taken by Southwest airlines in their relentless pursuit of being a low-cost airline by making trade-offs of meals, firstclass service etc.

Trade-offs are real, straddling strageies that force us to make sacrifices on the margins by default that we might not have made by desgin. The reality is, saying yes to any opportunity by definition requires saying no to several others.

#+begin_quote
“I didn’t start out with the goal of devoting all of myself to my job. It crept in over time. Each year that went by, slight modifications became the new normal. First I spent a half-hour on Sunday organizing my e-mail, to-do list, and calendar to make Monday morning easier. Then I was working a few hours on Sunday, then all day. My boundaries slipped away until work was all that was left.” --- Erin Callan
#+end_quote

We can either make the hard choices for ourselves or allow others to decide for us.

*We can try to avoid the reality of trade-offs, but we can't escape them.*

#+begin_quote
“I once worked with an executive team that needed help with their prioritization. They were struggling to identify the top five projects they wanted their IT department to complete over the next fiscal year, and one of the managers was having a particularly hard time with it. She insisted on naming eighteen “top priority” projects. I insisted that she choose five. She took her list back to her team, and two weeks later they returned with a list she had managed to shorten—by one single project! (I always wondered what it was about that one lone project that didn’t make the cut.) By refusing to make trade-offs, she ended up spreading five projects’ worth of time and effort across seventeen projects. Unsurprisingly, she did not get the results she wanted. Her logic had been: We can do it all. Obviously not.”
#+end_quote

A Nonessentialist approaches every trade-off by asking, "How can I do both?" Essentialists ask the thougher but ultimately more liberating question, "What problem do I want?"

#+begin_quote
"There are no solutions. There are only trade-offs" --- Thomas Sowell
#+end_quote

Like the Southwest, we can enjoy the success that results from making a consistent set of choices.

Essentialists see trade-offs as a inherent part of life, not as an inherently negative part of life. Instead of asking, "What do I have to give up?" they ask, "What do I want to go big on?"
* Escape

#+begin_quote
nonessentialist is too busy doing to think about life.
#+end_quote

#+begin_quote
essentialist creates space to escape and explore life.
#+end_quote

*In order to have focus we need to escape to focus.*

*** Space to concentrate

Think of Sir Isaac Newton. He spent two years working on what became /Principia Mathematica/, his famous writings on universal gravitation and the three laws of motion. This period of almost solitary confinement proved critical in what became a true breakthrough that shaped scientific thinking for the next three hundred years.

It seems obvious, but when did you last take time out of your busy day simply to sit and think? I'm talking about deliverately setting aside distraction-free time in a distraction-free space to do absolutely nothing other than think.



*** Space to read

Whether you can invets two hours a day, two weeks a yaer, or even just five minutes every morning, it is important to make space to escape in your busy life.

Bill Gates famously takes a regular week off from his daily duties at Microsoft simply to think and read.
* Look

*See What Really Matters*

Being a journalist of your own life will force you to stop hyper-focusing on all the minor details and see the bigger picture. You can apply the skills of a journalist no matter what field you are in—you can even apply them to your personal life. By training yourself to look for “the lead,” you will suddenly find yourself able to see what you have missed. You’ll be able to do more than simply see the dots of each day: you’ll also connect them to see the trends. Instead of just reacting to the facts, you’ll be able to focus on the larger issues that really matter.

Essentialists are powerful observers and listeners. Knowing that the reality of trade-offs means they can't possibly pay attention to everything, they listen deliberately for what is not being explicitly stated. They read between the lines.

*Keep a Journal*: You already know why.
* Play

“Play, which I would define as anything we do simply for the joy of doing rather than as a means to an end—whether it’s flying a kite or listening to music or throwing around a baseball—might seem like a nonessential activity. Often it is treated that way. But in fact play is essential in many ways. Stuart Brown, the founder of the National Institute for Play, has studied what are called the play histories of some six thousand individuals and has concluded that play has the power to significantly improve everything from personal health to relationships to education to organizations’ ability to innovate. “Play,” he says, “leads to brain plasticity, adaptability, and creativity.” As he succinctly puts it, “Nothing fires up the brain like play.”

+ Play broadens the range of options available to us.
+ It helps us to see the possibilities we otherwise wouldn't have made.
+ It opens our minds and broadens our perspectives.
+ It helps us challenge old assumptions and makes us more receptive to untested ideas.
+ It is an antidote to stress.
+ Play has a positive effect on the executive function of the brain.

#+begin_quote
Play doesn't just help us to explore what is essential. It is essential in and of itself.
#+end_quote
* Sleep

#+begin_quote
Each night, when I got to sleep, I die. And the next morning, when I wake up, I am reborn.
#+end_quote

** Protecting the asset

The best asset we have for making a contribution to the world is /ourselves/. If we underinvest in ourselves, and by that I mean our minds, our bodies, and our spirits, we damage the very tool we need to make our highest contribution. One of the most common ways people - especially ambitious, successful people - damage this asset is through a lack of sleep.

For a type A personality, it is not hard to push oneself hard. Pushing oneself to the limit is easy. The real challenge for the person who thrives on challenges is not to work hard.

Sleep is not the enemy of productivity, in fact sleep is the driver of peak performance.

While there clearly are people who can survive on fewer hours of sleep, most of them are just used to being tired they have forgotten what it really feels like to be fully rested.


While we sleep our brains are hard at work encoding and restructuring information. Therefore when we wake up, our brains may have made new neural connections, thereby opening up a broader range of solutions to problems, literally overnight. Sleep is what allows us to operate at our highest level of concetration so that we can achieve more, in less time.

#+begin_quote
Our highest priority is to protect our ability to prioritize.
#+end_quote
* Select

#+begin_quote
If the answer isn't a definite yes then it should be no.
#+end_quote

+ What opportunity is being offered to you?
+ What are your minimum criteria for this option to be considered?
+ What are the ideal criteria for this option to be approved?

Write down a list of three "minimum criteria" and a list of three "ideal criteria". If the opportunity doesn't pass the first set of criteria, the answer is obviously no. But if it also doesn't pass two of your three extreme/ideal criteria, the answer is still no.

** Eliminate

If I didn't ahve this opportunity, what would I be willing to do to acquire it?

What is the price you would be willing to pay for it? Should you hold on or let go?
* Clarify

+ When there is a lack of clarity, people waste time and energy on the trivial many. When they have sufficient levels of clarity, they are capable of greater breakthroughs and innovations.

** Common Patterns when there is lack of clarity
*** Playing politics

+ When the end goal is unclear, team becomes focused on making their own game to come up as better than their peers in front of the manager.
+ When our personal goals are unclear we waste our energy tring to look good in comparison to other people.
*** It's All Good (Which is bad)

+ Teams without purpose become leaderless and pursue things that advance their own short-term interests.
** Essential intent

+ An essential intent is one decision that settles one thousand later decisions.
+ It is both inspirational and concrete, both meaningful and measurable.
+ It's like deciding you're going to become a doctor instead of a lawyer.
+ Ask, "How will we know when we are done?"
+ Is not vague, it's the difference between "eliminating hunger in the world" and "“to build 150 affordable, green, storm-resistant homes for families living in the Lower 9th Ward”
* Dare

#+begin_quote
The right "no" spoken at the right time can change the course of history"
#+end_quote

+ Have you ever felt the conflict between your internal conviction and an external action?
+ Have you ever said yes when you meant no simply to avoid conflit or friction?
+ Have you ever felt too scared or timid to turn down an invitation or request from a boss, colleague, friend, neighbor, or family member for fear of disappointing them?

  You are not alone.

  Anyone can talk about focusing only on essentials, but only a few dare to do so. There are good reasons against saying no. There is FOMO, social awkwardness, the human want to get along with others.

  The only way out of this trap is to learn to say no firmly, resolutely, and yet gracefully. Once we do so, we find that our fears are greatly exaggerated and people actually respect us more.

  The point is to say to no the nonessentials so we can say yes to the things that really matter.

** How to actually say no?

+ Separate the decision from the relationship
+ You don't have to use the word "no" and can paraphrase
+ Focus on the trade-off
+ Remind yourself that everyone is selling something.
+ Make your peace with the fact that saying "no" often requires trading popularity for respect.
+ Remember that clear "no" can be more graceful than a vague or noncommittal "yes".
* Uncommit

#+begin_quote
/Sunk-cost bias/ is the tendancey to continue to invest time, money, or energy into something we know is a losing proposition simply because we have already incurred, or sunk, a cost that cannot be recouped.
#+end_quote

Sunk cost explains why we would sit through a terrible movie because we paid for the tickets. It explains why we invest in a toxic relationship even when our efforts only make things worse.

A nonessentialist has the courage and confidence to admit his or her mistakes and uncommit, no matter the sunk costs.

** Avoiding Commitment Traps

*Endowment Effect*: our tendancy to undervalue things that aren't ours and to overvalue things because we already own them.

Think about the book in your shelves that you haven't read in years, the clothes that you never wore. Instead of asking "How much I value this item?" ask "If I did not own this item, how much would I pay to obtain it?".

Only when we admit we have made a mistake in commiting to something can we make a mistake a part of our past. There should be no shame in admitting to a mistake; after all, we really are only admitting that we are now wiser than we once were.

*Status Quo Bias*: the tendancy to continue doing something simply because we have always done it is sometimes called the "status quo bias." An antidote to status quo bias is [[https://www.investopedia.com/terms/z/zbb.asp][zero-based budgeting]].

Another idea that can be used to eliminate nonessentials is [[https://exclusive.multibriefs.com/content/creative-leaders-embrace-the-reverse-pilot][reverse pilot]].
* Edit

#+begin_quote
“An editor is not merely someone who says no to things. A three-year-old can do that. Nor does an editor simply eliminate; in fact, in a way, an editor actually adds. What I mean is that a good editor is someone who uses deliberate subtraction to actually add life to the ideas, setting, plot, and characters.”
#+end_quote

** Editing Life

+ Cut out options
+ Condense: "If I had more time I would have written a shorter letter."
+ correct, not just cut or condence
+ edit less, you don' have to edit everything
* Limit

#+begin_quote
No is a complete sentence. Boundaries are important.
#+end_quote

Boundaries are a little like walls of a sandcastle. The second we let one fall over, the rest of them come crashing down. If you make a exception once, then you might have made it several times.

Remember, their problem is not your problem. We sure should help other people, but when they make their problem our problem, we aren't helping them; we are enabling them.

When we have clear boundaries, we are free to select from the whole area - or the whole range of options - that we have deliberately chosen to explore.

** Dealbreakers

Make a list of your dealbreakers. Dealbreakers are the types of requests that you simply refuse to say yes to unless they somehow overlap with your own priorities or agenda. Write down any time you feel violated or put upon by someone's request.
* Buffer

Invest time you have saved by eliminating the nonessentials into designing a system to make execution almost effortless. Here we explore how to make executing the right things as easy and frictionless as possible.

We live in a unpredictable world. The only thing that is pridictable is the unexpected. We can either wait for the moment and react or we can prepare. We can create a buffer.

A buffer is anything that prevents two things from coming into contact and harming each other.

We all know those people who chronically underestimate how long something will really take, yet inevitably these things end up taking longer. When this happens they are reacting to the problem and hence results suffer.

As an essentialist you have to look ahead and prepare for contingencies, expect the unexpected. You have to use the good times to create a buffer for the bad.

- Use *extreme preparation*.
- Add 50 percent to your time estimate.
* Subtract

The question is, "What is the obstacle that is keeping you back from achieving what really matters to you?". By indentifying adn removing this "constraint" you'll be able to significantly reduce the friction keeping you from executing what is essential. Instead of quickfix solutions focus on making one-time investment in removing obstacles.

- make the end goal clear (essential intent)
- indentify the sloweset hiker (a parallel execution is only as fast as the slowest thread)
- remove the obstacle
* Progress

The nonessentialist operates under the false logic that the more he strives, the more he will achieve, but the reality is, the more we reach for the stars, the harder it is to get ourselves off the ground. The essentialist pursues small and simple wins in areas that are essential.

Research has shown that of all forms of human motivation teh most effective one is progress. A small, concrete win creates momentum and affirms our faith in our further success.

Instead of starting big and then flaring out with nothing to show for it other than time and energy wasted, to really get essential things done we need to start small and build momentum. Then we can use that momentum to work toward the next win, and the next one and so on until we have a significant breakthrough - and when we do, our progress will have become so frictionless and effortless that the breakthrough will seem like overnight success.

- focus on minimal viable progress (done is better than perfect).
- do the minimal viable preparation (start early and small or start late and big).
- visually reward the progress (don't underestimate effects of visalization).
* Flow

- Check out [[https://balancethegrind.co/daily-routines/michael-phelps-daily-routine/][Michael Phelps's race routine]].

The essentialist designs a routine that makes achieving what you have identified as essential the default position. Execution is not a matter of raw effort alone.

** Making it look easy

Routine is one of the most powerful tools for removing obstacles. Create a routine around the essentials and you only have to execute them on autopilot. Instead of consciously the essential, it will happen without our having to think about it.

Mihaly demonstrates how creative people have strict routines to free up their minds.

#+begin_quote
Most creative individuals find out early what their best rythms are for sleeping, eating, and working, and abide by them even when it is tempting to do otherwise. They wear clothes that are comfortable, they interact only with people they find congenial, they do only things they think are important.
#+end_quote

Personalizing patterns of actions helps free the mind from the expectations that make demands on attention and allows intense concentration on matters that count.

This section repeats advice from "Atomic Habits" and "The Power of Habit".

- do the most difficult thing first. "We already have too much to think about. Why not eliminate some of them by establishing a routine?"
* Focus

#+begin_quote
Life is available only in the present moment. If you abandon the present moment you cannot life the moments of your daily life deeply.
#+end_quote

** There is only now

It's natural and human to obses over past mistakes or feel stress about what may be ahead of us. Yet every second spent worrying about a past or future moment distracts us from what is important in the here and now.

We can learn from the past and imagine the future. Yet only in the here and now can we actually exectue the things that really matter.

** Figure out what is most important thing right now

When faced with so many tasks and obligations that you can't figure out which to tackle first, stop. Take a deep breath. Get present in the moment and ask yourself what is most important this very second - not what's most important tomorrow or even an hour from now. If you're not sure, make a list of everything vying for your attention and cross off anything that is not important right now.
** Pause that refreshes

We all know this feeling. We may have left the office physically, but we are very muchs tlil there mentally, as our minds get caught in the endless loop of replaying the events of today and worring about all the things we need to get done the following day.

Close your eyes, breathe in and out once: deeply and slowly. As you exhale, let the work issues fall away.
* Be

Essentialism can be something you do occasionally, or something you are.

#+begin_quote
Less but better.
#+end_quote

There is a big difference between a nonessentialist who happens to apply essentialism and a essentialist who occasionally slips back to some nonessentialist practices.

People with essentialism at their core get far more from their investment than those who absorb it only at the surface level. When we look back on our careers and our lives, would we rather see a long laundry list of "accomplishments" that don't really matter or just a few major accomplishments that have real meaning and significance?

Once you become a essentialist, you will find that you aren't like everybody else. When we look back on our careers and our lives, would we rather see a long laundry list of "accomplishments" that don't really matter or just a few major accomplishments that have real meaning and significance?

Once you become a essentialist, you will find that you aren't like everybody else. When other people are saying yes, you will find yourself saying no.

Focusing on essentials is a choice. It is your choice. That in itself is liberating.

*Some benefits of essentialism*

- more clarity
- more control
- more joy in the journey

Finally quoting the last section of the book:

The life of an Essentialist is a life of meaning. It is a life that really matters.
When I need a reminder of this I think of a story. It is about a man whose three-year-old daughter died. In his grief he put together a video of her short little life. But as he went through all of his home videos he realized something was missing. He had taken video of every outing they had gone on and every trip they had taken. He had lots of footage—that wasn’t the problem. But then he realized that while he had plenty of footage of the places they had gone—the sights they had seen, the views they had enjoyed, the meals they had eaten, and the landmarks they had visited—he had almost no close-up footage of his daughter herself. He had been so busy recording the surroundings he had failed to record what was essential.
This story captures the two most personal learnings that have come to me on the long journey of writing this book. The first is the exquisitely important role of my family in my life. At the very, very end, everything everything else will fade into insignificance by comparison. The second is the pathetically tiny amount of time we have left of our lives. For me this is not a depressing thought but a thrilling one. It removes fear of choosing the wrong thing. It infuses courage into my bones. It challenges me to be even more unreasonably selective about how to use this precious—and precious is perhaps too insipid of a word—time. I know of someone who visits cemeteries around the world when he travels. I thought this was odd at first, but now I realize that this habit keeps his own mortality front and center.

The life of an Essentialist is a life lived without regret. If you have correctly identified what really matters, if you invest your time and energy in it, then it is difficult to regret the choices you make. You become proud of the life you have chosen to live.
Will you choose to live a life of purpose and meaning, or will you look back on your one single life with twinges of regret? If you take one thing away from this book, I hope you will remember this: whatever decision or challenge or crossroads you face in your life, simply ask yourself, “What is essential?” Eliminate everything else.
If you are ready to look inside yourself for the answer to this question, then you are ready to commit to the way of the Essentialist.
